name: Java CI with Maven

on:
  workflow_dispatch:
    inputs:
      browser:
        description: 'Choose Browser:'
        required: true
        default: 'Chrome'
        type: choice
        options:
          - 'Chrome'
          - 'Edge'
          - 'Firefox'
        threads:
          description: 'Choose number of Threads: (1-4)'
          required: true
          default: 1
          type: number
          
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Run Regression Suite
      run: mvn clean install -Dbrowser=${{ github.events.inputs.browser}} -Dthreads=${{github.events.inputs.threads}} -Dcicd=true
